
#
# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2026. This work has been developed by the National Digital Twin Programme and is legally
# attributed to the UK's Department for Business, Innovation, Science and Trade (BIST) as the governing entity.
#

# Build stage
ARG JAR_FILE=management-node-1.1.0.jar
FROM maven:3.9.14-eclipse-temurin-21-alpine AS build
ARG JAR_FILE
WORKDIR /build

# Copy the project files
COPY pom.xml .
COPY src ./src

# Build the application
RUN mvn clean package -DskipTests

# Runtime stage
FROM eclipse-temurin:23-jdk-alpine
ARG JAR_FILE

RUN addgroup -S app && adduser -S -G app -u 10001 app

WORKDIR /app

RUN chown -R app:app /app

# Copy application jar from build stage and certificates
COPY --from=build /build/target/${JAR_FILE} /app/app.jar
COPY docker/keystore.jks /app/keystore.jks
COPY docker/truststore.jks /app/truststore.jks

RUN chown app:app /app/app.jar

# Use non-root user from here on
USER app:app

# Set default certificate password
ENV CERTPASSWORD=changeit

EXPOSE 8090

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
